services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - /internal/infrastructure/jwt
    depends_on:
      - db
      - db_test
      - redis

  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db_prod_data:/var/lib/postgresql/data

  db_test:
    image: postgres:16
    container_name: db_test
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: mahouradb_test
    ports:
      - "5433:5432"
    volumes:
      - ./db_test_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-db
    restart: unless-stopped
    ports:
      - "${RDB_PORT}:${RDB_PORT}"
