global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "afiroozi007@gmail.com"
  smtp_auth_username: "afiroozi007@gmail.com"
  smtp_auth_password: "uckjnwsderchynci"
  smtp_require_tls: true

route:
  group_by: ["alertname", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "all-alerts"
  routes:
    - match:
        severity: critical
      receiver: "all-alerts"

receivers:
  - name: "all-alerts"
    email_configs:
      - to: "afiroozi007@gmail.com"
        send_resolved: true
    telegram_configs:
      - bot_token: "7643934949:AAEty9FDSmPO8lMdF4T5WzV4GKM7VJF1HpQ"
        chat_id: 500161862
        message: |
          {{ range .Alerts }}
          *{{ .Status | toUpper }}* — {{ .Labels.alertname }}
          {{ .Annotations.summary }}
          {{ .Annotations.description }}
          {{ end }}
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ["alertname"]
