// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Mahoura-shop/Backend/bootstrap"
	"github.com/Mahoura-shop/Backend/internal/application/service"
	"github.com/Mahoura-shop/Backend/internal/application/usecase"
	"github.com/Mahoura-shop/Backend/internal/domain/communication"
	logger2 "github.com/Mahoura-shop/Backend/internal/domain/logger"
	postgres2 "github.com/Mahoura-shop/Backend/internal/domain/repository/postgres"
	redis2 "github.com/Mahoura-shop/Backend/internal/domain/repository/redis"
	"github.com/Mahoura-shop/Backend/internal/domain/s3"
	"github.com/Mahoura-shop/Backend/internal/infrastructure/communication/email"
	"github.com/Mahoura-shop/Backend/internal/infrastructure/communication/sms"
	"github.com/Mahoura-shop/Backend/internal/infrastructure/database"
	"github.com/Mahoura-shop/Backend/internal/infrastructure/jwt"
	"github.com/Mahoura-shop/Backend/internal/infrastructure/localization"
	"github.com/Mahoura-shop/Backend/internal/infrastructure/logger"
	"github.com/Mahoura-shop/Backend/internal/infrastructure/repository/postgres"
	"github.com/Mahoura-shop/Backend/internal/infrastructure/repository/redis"
	"github.com/Mahoura-shop/Backend/internal/infrastructure/seed"
	"github.com/Mahoura-shop/Backend/internal/infrastructure/storage"
	"github.com/Mahoura-shop/Backend/internal/presentation/controller/v1/address"
	"github.com/Mahoura-shop/Backend/internal/presentation/controller/v1/brand"
	"github.com/Mahoura-shop/Backend/internal/presentation/controller/v1/cart"
	"github.com/Mahoura-shop/Backend/internal/presentation/controller/v1/category"
	"github.com/Mahoura-shop/Backend/internal/presentation/controller/v1/currency"
	"github.com/Mahoura-shop/Backend/internal/presentation/controller/v1/order"
	"github.com/Mahoura-shop/Backend/internal/presentation/controller/v1/product"
	"github.com/Mahoura-shop/Backend/internal/presentation/controller/v1/test"
	"github.com/Mahoura-shop/Backend/internal/presentation/controller/v1/user"
	"github.com/Mahoura-shop/Backend/internal/presentation/middleware"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApplication(container *bootstrap.Config) (*Application, error) {
	bootstrapDatabase := ProvideDBConfig(container)
	postgresDatabase := database.NewPostgresDatabase(bootstrapDatabase)
	bootstrapRedis := ProvideRDBConfig(container)
	redisDatabase := database.NewRedisDatabase(bootstrapRedis)
	wireDatabase := &Database{
		DB:  postgresDatabase,
		RDB: redisDatabase,
	}
	constants := ProvideConstants(container)
	otp := ProvideOTPConfig(container)
	userCacheRepository := redis.NewUserCacheRepository(redisDatabase)
	otpService := service.NewOTPService(constants, otp, userCacheRepository)
	keyManager := jwt.NewJWTKeyManager()
	jwtKeysPath := ProvideJWTKeysPath(container)
	jwtService := service.NewJWTService(keyManager, jwtKeysPath)
	smsGateway := ProvideSMSGatewayConfig(container)
	smsTemplates := ProvideSMSTemplates(container)
	smsService := sms.NewSMSService(smsGateway, smsTemplates)
	emailAccount := ProvideEmailSenderAccount(container)
	emailTemplates := ProvideEmailTemplates(container)
	emailService := email.NewEmailService(emailAccount, emailTemplates)
	userRepository := postgres.NewUserRepository()
	categoryRepository := postgres.NewCategoryRepository()
	brandRepository := postgres.NewBrandRepository()
	productRepository := postgres.NewProductRepository()
	walletRepository := postgres.NewWalletRepository()
	cartRepository := postgres.NewCartRepository()
	transactionRepository := postgres.NewTransactionRepository()
	userServiceDeps := service.UserServiceDeps{
		Constants:             constants,
		OTPService:            otpService,
		JWTService:            jwtService,
		SMSService:            smsService,
		EmailService:          emailService,
		UserRepository:        userRepository,
		CategoryRepository:    categoryRepository,
		BrandRepository:       brandRepository,
		ProductRepository:     productRepository,
		WalletRepository:      walletRepository,
		CartRepository:        cartRepository,
		TransactionRepository: transactionRepository,
		UserCacheRepository:   userCacheRepository,
		DB:                    postgresDatabase,
	}
	userService := service.NewUserService(userServiceDeps)
	generalUserController := user.NewGeneralUserController(constants, userService, jwtService)
	addressRepository := postgres.NewAddressRepository()
	addressService := service.NewAddressService(constants, addressRepository, postgresDatabase)
	generalAddressController := address.NewGeneralAddressController(constants, addressService)
	testService := service.NewTestService(constants, postgresDatabase)
	generalTestController := test.NewGeneralTestController(constants, testService)
	generalControllers := &GeneralControllers{
		UserController:    generalUserController,
		AddressController: generalAddressController,
		TestController:    generalTestController,
	}
	customerUserController := user.NewCustomerUserController(constants, userService)
	customerAddressController := address.NewCustomerAddressController(constants, addressService)
	s3 := ProvideStorageConfig(container)
	s3Storage := storage.NewS3Storage(constants, s3)
	categoryServiceDeps := service.CategoryServiceDeps{
		Constants:          constants,
		CategoryRepository: categoryRepository,
		S3Storage:          s3Storage,
		DB:                 postgresDatabase,
	}
	categoryService := service.NewCategoryService(categoryServiceDeps)
	brandServiceDeps := service.BrandServiceDeps{
		Constants:       constants,
		BrandRepository: brandRepository,
		S3Storage:       s3Storage,
		DB:              postgresDatabase,
	}
	brandService := service.NewBrandService(brandServiceDeps)
	currencyRepository := postgres.NewCurrencyRepository()
	currencyServiceDeps := service.CurrencyServiceDeps{
		Constants:          constants,
		CurrencyRepository: currencyRepository,
		S3Storage:          s3Storage,
		DB:                 postgresDatabase,
	}
	currencyService := service.NewCurrencyService(currencyServiceDeps)
	productServiceDeps := service.ProductServiceDeps{
		Constants:         constants,
		ProductRepository: productRepository,
		CategoryService:   categoryService,
		BrandService:      brandService,
		CurrencyService:   currencyService,
		S3Storage:         s3Storage,
		DB:                postgresDatabase,
	}
	productService := service.NewProductService(productServiceDeps)
	cartServiceDeps := service.CartServiceDeps{
		Constants:         constants,
		CartRepository:    cartRepository,
		ProductRepository: productRepository,
		UserService:       userService,
		ProductService:    productService,
		S3Storage:         s3Storage,
		DB:                postgresDatabase,
	}
	cartService := service.NewCartService(cartServiceDeps)
	customerCartController := cart.NewCustomerCartController(constants, cartService)
	orderRepository := postgres.NewOrderRepository()
	paymentRepository := postgres.NewPaymentRepository()
	instalmentRepository := postgres.NewInstalmentRepository()
	zarinpal := ProvideZarinpalConfig(container)
	paymentService := service.NewPaymentService(zarinpal)
	orderServiceDeps := service.OrderServiceDeps{
		Constants:             constants,
		OrderRepository:       orderRepository,
		ProductRepository:     productRepository,
		WalletRepository:      walletRepository,
		TransactionRepository: transactionRepository,
		PaymentRepository:     paymentRepository,
		InstalmentRepository:  instalmentRepository,
		AddressRepository:     addressRepository,
		CurrencyService:       currencyService,
		ProductService:        productService,
		UserService:           userService,
		CartService:           cartService,
		PaymentService:        paymentService,
		SMSService:            smsService,
		DB:                    postgresDatabase,
	}
	orderService := service.NewOrderService(orderServiceDeps)
	customerOrderController := order.NewCustomerOrderController(constants, orderService)
	customerControllers := &CustomerControllers{
		UserController:    customerUserController,
		AddressController: customerAddressController,
		CartController:    customerCartController,
		OrderController:   customerOrderController,
	}
	pagination := ProvidePaginationConfig(container)
	adminCategoryController := category.NewAdminCategoryController(constants, pagination, categoryService)
	adminCurrencyController := currency.NewAdminCurrencyController(constants, pagination, currencyService)
	adminBrandController := brand.NewAdminBrandController(constants, pagination, brandService)
	adminProductController := product.NewAdminProductController(constants, pagination, productService)
	adminUserController := user.NewAdminUserController(constants, pagination, userService)
	adminOrderController := order.NewAdminOrderController(constants, orderService)
	adminControllers := &AdminControllers{
		CategoryController: adminCategoryController,
		CurrencyController: adminCurrencyController,
		BrandController:    adminBrandController,
		ProductController:  adminProductController,
		UserController:     adminUserController,
		OrderController:    adminOrderController,
	}
	controllers := &Controllers{
		General:  generalControllers,
		Customer: customerControllers,
		Admin:    adminControllers,
	}
	authMiddleware := middleware.NewAuthMiddleware(constants, jwtService, userRepository, postgresDatabase)
	corsMiddleware := middleware.NewCorsMiddleware()
	recoveryMiddleware := middleware.NewRecovery(constants)
	translator := localization.NewTranslationService()
	localizationMiddleware := middleware.NewLocalization(constants, translator)
	rateLimit := ProvideRateLimitConfig(container)
	rateLimitMiddleware := middleware.NewRateLimit(rateLimit)
	bootstrapLogger := ProvideLoggerConfig(container)
	loggerLogger, err := logger.NewLogger(bootstrapLogger, constants)
	if err != nil {
		return nil, err
	}
	loggerMiddleware := middleware.NewLoggerMiddleware(loggerLogger)
	middlewares := &Middlewares{
		Authentication: authMiddleware,
		CORS:           corsMiddleware,
		Recovery:       recoveryMiddleware,
		Localization:   localizationMiddleware,
		RateLimit:      rateLimitMiddleware,
		Logger:         loggerMiddleware,
	}
	addressSeeder := seed.NewAddressSeeder(addressRepository, postgresDatabase)
	adminCredentials := ProvideSuperAdminCredential(container)
	adminSeeder := seed.NewAdminSeeder(adminCredentials, userRepository, postgresDatabase)
	currencySeeder := seed.NewCurrencySeeder(currencyRepository, postgresDatabase)
	seeds := &Seeds{
		AddressSeeder:  addressSeeder,
		AdminSeeder:    adminSeeder,
		CurrencySeeder: currencySeeder,
	}
	application := NewApplication(wireDatabase, controllers, middlewares, seeds)
	return application, nil
}

// wire.go:

var DatabaseProviderSet = wire.NewSet(database.NewPostgresDatabase, database.NewRedisDatabase, wire.Bind(new(database.Database), new(*database.PostgresDatabase)), wire.Bind(new(database.Cache), new(*database.RedisDatabase)), wire.Struct(new(Database), "*"))

var RepositoryProviderSet = wire.NewSet(postgres.NewUserRepository, postgres.NewAddressRepository, postgres.NewCategoryRepository, postgres.NewCurrencyRepository, postgres.NewBrandRepository, postgres.NewProductRepository, postgres.NewWalletRepository, postgres.NewCartRepository, postgres.NewOrderRepository, postgres.NewTransactionRepository, postgres.NewPaymentRepository, postgres.NewInstalmentRepository, redis.NewUserCacheRepository, wire.Bind(new(postgres2.UserRepository), new(*postgres.UserRepository)), wire.Bind(new(postgres2.AddressRepository), new(*postgres.AddressRepository)), wire.Bind(new(redis2.UserCacheRepository), new(*redis.UserCacheRepository)), wire.Bind(new(postgres2.CategoryRepository), new(*postgres.CategoryRepository)), wire.Bind(new(postgres2.CurrencyRepository), new(*postgres.CurrencyRepository)), wire.Bind(new(postgres2.BrandRepository), new(*postgres.BrandRepository)), wire.Bind(new(postgres2.ProductRepository), new(*postgres.ProductRepository)), wire.Bind(new(postgres2.WalletRepository), new(*postgres.WalletRepository)), wire.Bind(new(postgres2.CartRepository), new(*postgres.CartRepository)), wire.Bind(new(postgres2.OrderRepository), new(*postgres.OrderRepository)), wire.Bind(new(postgres2.TransactionRepository), new(*postgres.TransactionRepository)), wire.Bind(new(postgres2.PaymentRepository), new(*postgres.PaymentRepository)), wire.Bind(new(postgres2.InstalmentRepository), new(*postgres.InstalmentRepository)))

var ServiceProviderSet = wire.NewSet(wire.Struct(new(service.UserServiceDeps), "*"), wire.Struct(new(service.CategoryServiceDeps), "*"), wire.Struct(new(service.CurrencyServiceDeps), "*"), wire.Struct(new(service.BrandServiceDeps), "*"), wire.Struct(new(service.ProductServiceDeps), "*"), wire.Struct(new(service.CartServiceDeps), "*"), wire.Struct(new(service.OrderServiceDeps), "*"), service.NewUserService, service.NewOTPService, sms.NewSMSService, email.NewEmailService, service.NewJWTService, service.NewAddressService, service.NewTestService, service.NewCategoryService, service.NewCurrencyService, service.NewBrandService, service.NewProductService, service.NewCartService, service.NewOrderService, service.NewPaymentService, wire.Bind(new(usecase.UserService), new(*service.UserService)), wire.Bind(new(usecase.OTPService), new(*service.OTPService)), wire.Bind(new(communication.SMSService), new(*sms.SMSService)), wire.Bind(new(communication.EmailService), new(*email.EmailService)), wire.Bind(new(usecase.JWTService), new(*service.JWTService)), wire.Bind(new(usecase.AddressService), new(*service.AddressService)), wire.Bind(new(usecase.TestService), new(*service.TestService)), wire.Bind(new(usecase.CategoryService), new(*service.CategoryService)), wire.Bind(new(usecase.CurrencyService), new(*service.CurrencyService)), wire.Bind(new(usecase.BrandService), new(*service.BrandService)), wire.Bind(new(usecase.ProductService), new(*service.ProductService)), wire.Bind(new(usecase.CartService), new(*service.CartService)), wire.Bind(new(usecase.OrderService), new(*service.OrderService)), wire.Bind(new(usecase.PaymentService), new(*service.PaymentService)))

var AdapterProviderSet = wire.NewSet(localization.NewTranslationService, logger.NewLogger, storage.NewS3Storage, jwt.NewJWTKeyManager, wire.Bind(new(logger2.Logger), new(*logger.Logger)), wire.Bind(new(s3.S3Storage), new(*storage.S3Storage)))

var GeneralControllerProviderSet = wire.NewSet(user.NewGeneralUserController, address.NewGeneralAddressController, test.NewGeneralTestController, wire.Struct(new(GeneralControllers), "*"))

var CustomerControllerProviderSet = wire.NewSet(user.NewCustomerUserController, address.NewCustomerAddressController, cart.NewCustomerCartController, order.NewCustomerOrderController, wire.Struct(new(CustomerControllers), "*"))

var AdminControllerProviderSet = wire.NewSet(currency.NewAdminCurrencyController, category.NewAdminCategoryController, brand.NewAdminBrandController, product.NewAdminProductController, user.NewAdminUserController, order.NewAdminOrderController, wire.Struct(new(AdminControllers), "*"))

var ControllersProviderSet = wire.NewSet(wire.Struct(new(Controllers), "*"))

var MiddlewareProviderSet = wire.NewSet(middleware.NewAuthMiddleware, middleware.NewCorsMiddleware, middleware.NewRecovery, middleware.NewLocalization, middleware.NewRateLimit, middleware.NewLoggerMiddleware, wire.Struct(new(Middlewares), "*"))

var SeederProviderSet = wire.NewSet(seed.NewAddressSeeder, seed.NewAdminSeeder, seed.NewCurrencySeeder, wire.Struct(new(Seeds), "*"))

func ProvideConstants(container *bootstrap.Config) *bootstrap.Constants {
	return container.Constants
}

func ProvideLoggerConfig(container *bootstrap.Config) *bootstrap.Logger {
	return &container.Env.Logger
}

func ProvideStorageConfig(container *bootstrap.Config) *bootstrap.S3 {
	return &container.Env.Storage
}

func ProvideRateLimitConfig(container *bootstrap.Config) *bootstrap.RateLimit {
	return &container.Env.RateLimit
}

func ProvideDBConfig(container *bootstrap.Config) *bootstrap.Database {
	return &container.Env.PrimaryDB
}

func ProvideRDBConfig(container *bootstrap.Config) *bootstrap.Redis {
	return &container.Env.PrimaryRedis
}

func ProvideOTPConfig(container *bootstrap.Config) *bootstrap.OTP {
	return &container.Env.OTP
}

func ProvideSMSGatewayConfig(container *bootstrap.Config) *bootstrap.SMSGateway {
	return &container.Env.SMSGateway
}

func ProvideSMSTemplates(container *bootstrap.Config) *bootstrap.SMSTemplates {
	return &container.Constants.SMSTemplates
}

func ProvideJWTKeysPath(container *bootstrap.Config) *bootstrap.JWTKeysPath {
	return &container.Constants.JWTKeysPath
}

func ProvideEmailTemplates(container *bootstrap.Config) *bootstrap.EmailTemplates {
	return &container.Constants.EmailTemplates
}

func ProvidePaginationConfig(container *bootstrap.Config) *bootstrap.Pagination {
	return &container.Env.Pagination
}

func ProvideWebsocketSetting(container *bootstrap.Config) *bootstrap.WebsocketSetting {
	return &container.Env.WebsocketSetting
}

func ProvideEmailSenderAccount(container *bootstrap.Config) *bootstrap.EmailAccount {
	return &container.Env.EmailSenderAccount
}

func ProvideSuperAdminCredential(container *bootstrap.Config) *bootstrap.AdminCredentials {
	return &container.Env.Admins
}

func ProvideZarinpalConfig(container *bootstrap.Config) *bootstrap.Zarinpal {
	return &container.Env.Zarinpal
}

type Database struct {
	DB  database.Database
	RDB database.Cache
}

type GeneralControllers struct {
	UserController    *user.GeneralUserController
	AddressController *address.GeneralAddressController
	TestController    *test.GeneralTestController
}

type CustomerControllers struct {
	UserController    *user.CustomerUserController
	AddressController *address.CustomerAddressController
	CartController    *cart.CustomerCartController
	OrderController   *order.CustomerOrderController
}

type AdminControllers struct {
	CategoryController *category.AdminCategoryController
	CurrencyController *currency.AdminCurrencyController
	BrandController    *brand.AdminBrandController
	ProductController  *product.AdminProductController
	UserController     *user.AdminUserController
	OrderController    *order.AdminOrderController
}

type Controllers struct {
	General  *GeneralControllers
	Customer *CustomerControllers
	Admin    *AdminControllers
}

type Middlewares struct {
	Authentication *middleware.AuthMiddleware
	CORS           *middleware.CORSMiddleware
	Recovery       *middleware.RecoveryMiddleware
	Localization   *middleware.LocalizationMiddleware
	RateLimit      *middleware.RateLimitMiddleware
	Logger         *middleware.LoggerMiddleware
}

type Seeds struct {
	AddressSeeder  *seed.AddressSeeder
	AdminSeeder    *seed.AdminSeeder
	CurrencySeeder *seed.CurrencySeeder
}

type Application struct {
	Database    *Database
	Controllers *Controllers
	Middlewares *Middlewares
	Seeds       *Seeds
}

func NewApplication(database2 *Database,
	controllers *Controllers,
	middlewares *Middlewares,
	seeds *Seeds,
) *Application {
	return &Application{
		Database:    database2,
		Controllers: controllers,
		Middlewares: middlewares,
		Seeds:       seeds,
	}
}
